### ISSUE TITLE
Can't Run The App (AUR Wayland)

### ISSUE THREAD

**Issue by Pipenguim** [jeffshee/hidamari#106]
(Arch, Hyprland, Nvidia)
I tried installing hidamari today, and I'm getting an error about the "commons" library whenever I try to run it as can be seen in the screenshot below. I found it weird, and even after checking all the dependencies for the package and installing everything again, I am still getting the same error.
![image](https://github.com/jeffshee/hidamari/assets/70240564/b8c88270-bb75-4201-a712-27de0133a084)
I figured I didn't have the library since that's what the error seemed to indicate. The problem was that when I tried installing it from pip, I got the error shown in the screenshot below.
![image](https://github.com/jeffshee/hidamari/assets/70240564/3622cb44-88c2-4020-9e2e-fc38bbf69e58)
Not quite sure why this is happening. I am currently running mpvpaper so this could maybe be causing it? I assume not so I am a bit confused on why this is happening.
Thanks

**Comment by Pipenguim** [comment]
I was also able to install commons through python2.7, but I still get the same exact error when trying to run hidamari. I even restarted my computer and it does not want to work.
![image](https://github.com/jeffshee/hidamari/assets/70240564/76610147-ea5c-4569-8f55-6059215f7328)
![image](https://github.com/jeffshee/hidamari/assets/70240564/7f3bffa8-309d-4029-8eda-62a6243cd87e)

**Comment by Verghill2137** [comment]
Personally, running this command helped me:
sudo pacman -S webkit2gtk-4.1

**Comment by Pipenguim** [comment]
That actually worked, tysm!!!!!!!!!!!
@laymoth could you add webkit2gtk-4.1 as a dependency in the AUR?
Feel like that'll avoid a lot of future problems.
Thanks

**Comment by laymoth** [comment]
@Pipenguim Will be added soon :D
