### ISSUE TITLE
Hidmari Hyprland

### ISSUE THREAD

**Issue by LEAL-original** [jeffshee/hidamari#139]
Hidamari runs, however not as wallpaper
![image](https://github.com/jeffshee/hidamari/assets/72926600/60255906-12da-4fa6-9bb1-6637f5ae33a3)
I've tried both the AUR and the flatpak versions respectively:
when it comes the aur-ver I even tried running 'hidamari -b', but with no different result.

**Comment by jeffshee** [comment]
Hi @LEAL-original ,

Please check the opened issue before opening a new one, it's already reported here. #113
