### ISSUE TITLE
High CPU usage with display changes

### ISSUE THREAD

**Issue by Caioohv** [jeffshee/hidamari#149]
I use the same screen for two computers, and i change what input i am using by the screen.

I use Hidamari in Display 1, and other computer in Display 2.

When i am using just D1, there is no problem
But when i switch from D1 to D2, and then from D2 to D1, it almost doubles the CPU usage.

So, if i switch displays about 4 times, my computer just freezes because it uses 100% CPU

I think it is not suposed to be my CPU's fault, as it is an R5 5600g
I think it is not suposed to be my GPU's fault too, because i use a RTX2060

**Comment by Fengyuta-x** [comment]
About that I'd say... Config it to run on dgpu automatically in startup. You may configure bashrc for that, although it depends on your environment
