### ISSUE TITLE
not sure how to launch the program?

### ISSUE THREAD

**Issue by acme64** [jeffshee/hidamari#15]
I ran through the install, seems to have worked, but when i right click the background theres no button to launch.
if i run hidamari in terminal i get this:
```
~$ hidamari
Config JSON:
{'audio_volume': 0.5,
 'detect_maximized': True,
 'mute_audio': False,
 'static_wallpaper': True,
 'static_wallpaper_blur_radius': 5,
 'video_path': ''}
Traceback (most recent call last):
  File "/home/acme/bin/hidamari", line 18, in <module>
    Player()
  File "/home/acme/.hidamari/player.py", line 166, in __init__
    self.start_all_monitors()
  File "/home/acme/.hidamari/player.py", line 195, in start_all_monitors
    vlc_widget = VLCWidget(monitor.width, monitor.height)
  File "/home/acme/.hidamari/player.py", line 29, in __init__
    self.instance = vlc.Instance()
  File "/usr/local/lib/python3.9/dist-packages/vlc.py", line 1803, in __new__
    return libvlc_new(len(args), args)
  File "/usr/local/lib/python3.9/dist-packages/vlc.py", line 4969, in libvlc_new
    _Cfunction('libvlc_new', ((1,), (1,),), class_result(Instance),
  File "/usr/local/lib/python3.9/dist-packages/vlc.py", line 292, in _Cfunction
    raise NameError('no function %r' % (name,))
NameError: no function 'libvlc_new'
```

Not sure what to do?

**Comment by jeffshee** [comment]
Hi, 
The issue might be `vlc` isn't installed. I should have list that into dependency as well.

To install that, simply `sudo apt-get install vlc` if you are using Ubuntu, or `sudo dnf install vlc` if you are using Fedora.

BTW, by judging from your output, you are probably still using the v1 script. You might want to use the v2 one (released today) that has more feature.

**Comment by acme64** [comment]
that worked. I still don't see the right click menu item but I can launch it manually from command line. I'll update to v2 tonight

**Comment by jeffshee** [comment]
For the right click menu problem, please refer #11. 
For some unknown reason the right click menu doesn't show for some people. That's weird as it works perfectly on my system, so I can't debug it properly... I might consider adding another method to call the menu in the future ;)
