### ISSUE TITLE
[Flatpak] Adding videos to $HOME/Videos/Hidamari doesn't work

### ISSUE THREAD

**Issue by WasteOfO2** [jeffshee/hidamari#161]
Thank you for this project

I have been having trouble trying to add videos to Hidamari via flatpak

Uploading an image to show the same

![Niri 2024-07-06 03-11-43](https://github.com/jeffshee/hidamari/assets/45941793/75df21e8-4aaa-4966-af50-3173ba70b0f1)

**Comment by jeffshee** [comment]
Hi @WasteOfO2 
Hmm, have you tried the refresh button/restart the app?
Also, have you modified the permission of the Flatpak, or it was remained as default?

**Comment by WasteOfO2** [comment]
@jeffshee apparently it was the default permissions! however there seems to another issue, which i think would be more worth it as a separate issue. Thanks
