### ISSUE TITLE
Hidamari auto launch not working properly on Ubuntu 20.04

### ISSUE THREAD

**Issue by KleberMotta** [jeffshee/hidamari#17]
The application is executed but for some reason Hidamari doesn't load.

Using top or htop I can see that the process is running (and using 100% of a single thread of the processor, I wonder why)

I tried manually creating a systemd user service, same result.

The only thing I didn't try yet is a cron job.

**Comment by jeffshee** [comment]
Hi,
Thanks for your feedback.
Is the problem occurs only when auto launching Hidamari at login, or you can't launch the Hidamari normally as well?
It might be helpful if you can try run it in terminal, and paste the output here. Perhaps I can find some error here.

**Comment by KleberMotta** [comment]
Hi! I can run it normally using a desktop entry or command line. I just can't run it automatically after login, the app starts in the background, its process is shown and all, but it just doesn't start. Plus when this happens, apparently multiple instances of the application are running, at least that's what htop shows me. I would send you a log folder but couldn't find one.

**Comment by jeffshee** [comment]
Hmm, that’s weird.. Unfortunately I haven’t implement logging feature to the program, so there isn’t any log file generated right now. Currently, the only way to access the log is through launching the program using terminal. Maybe someday I will improve this.
For now, I will investigate this issue with Ubuntu 20.04 VM to see if there is any distro specific issue.
Thanks.

**Comment by jeffshee** [comment]
Hi, 
I tested with Ubuntu 20.04 in VM, and it seems that I couldn't reproduce the issue..
By any chance, are you using DE other than GNOME or other Ubuntu spin?
Also, could you attach the configuration file located at `~/.config/hidamari/hidamari.config`?
Thanks!

**Comment by KleberMotta** [comment]
Hi, I'm using gnome, maybe my Linux distro is tainted, IDK, 'cause it's a Dell computer shipped with Linux, but the issue is happening to me nonetheless. I'm sending the hidamari folder, but despite the result, I appreciate your effort in helping me, thanks!

[hidamari.config.zip](https://github.com/jeffshee/hidamari/files/6472310/hidamari.config.zip)

**Comment by jeffshee** [comment]
Hmm, I inspected the zip file that you provided, it was empty inside tho? (It only contains directories but not file) 😅

**Comment by KleberMotta** [comment]
Sorry man, I end up uninstalling it, but the config file was normal, I assure you. The app was working great! But the fact that I had to launch it manually threw me off. You can close the issue if want to, and sorry that I couldn't be of more help, Hidamari is a cool project! I tried others like it, wallset and komorebi, and def Hidamari was the best. All the best and good luck!

**Comment by jeffshee** [comment]
Sure! I will continue to improve the app and hopefully it will become more stable in the future~ 😊

**Comment by nicole-smartb** [comment]
Hi! I thought why not just open the same issue here rather than open a new one. So I also had the autostart problem, and tried to tinker around (on Ubuntu settings, not Hidamari source files).

So I found out that after first run of the app and chose a video/picture as desktop background, you need to 'quit Himadari" properly (that is via right click on desktop) to make sure Himadari run well at the next boot/restart. Also, at the Startup Application, you need to set the command to its main file `/usr/bin/Himadari`, otherwise you'll get `Error: Failed to create server` when launch via terminal.

I'm using Ubuntu 21.04 on Xorg for this, because I tried Himadari on Wayland and it doesn't work for me. Hope this help?

**Comment by jeffshee** [comment]
@nicole-smartb Hi, thanks for reporting!
Yep, let's reopen this issue. We need a better startup procedure.

**Comment by rounnus** [comment]
Hello, I do not know if I can help, but I had a similar problem and I fixed it by doing the following:
        **1)** I went to the **/usr/bin/** folder and i find the python file that called **hidamari**.
        **2)** I added 2 lines to the code that start the program so that it starts after 5 seconds.

I know not the best solution, but it fixes the problem (for me at least). 

```python3
#!/usr/bin/env python3
import server
import time

time.sleep(5)
server.run()

```

**Comment by jeffshee** [comment]
@rounnus Sure! Collaborations are always welcome. The good thing about OSS is that everyone can help. 😉
It might be the solution and also a good workaround for this issue IMO. I had noticed some apps like `conky` also use a short pause like this. Maybe it is required for a slower machine or some environment, that something might not have initialized properly when we run the server too early.
Thanks, I will work on this soon.

**Comment by jeffshee** [comment]
The initial fix is in master now 😃

**Comment by TheFeelTrain** [comment]
Even though you fixed it, you never made a new release for it. You have development up to October 2021 but the latest release is from May 2021.

**Comment by jeffshee** [comment]
@TheFeelTrain 
Sorry but right now I'm too busy for university... Maybe I'll be able to continue working on this project after this month.
Actually, I have some upcoming updates at `dev` branch already. But still, I'm lacking the time for polishing it as the final release...
(Is there anyone have the skill and interest to help? ;-) )
