### ISSUE TITLE
Gnome Runtime 44 end-of-life

### ISSUE THREAD

**Issue by shadyueh** [jeffshee/hidamari#170]
Hi, Jeff.
I'm not aware if you're already working on a migration. In any case, I'm getting warning about Gnome Runtime 44, saying the software needs to be updated to a supported runtime.

![image](https://github.com/user-attachments/assets/d8a92fde-51d9-4a19-8607-d669eebebe76)

Please disconsider it if already solved.
Thanks.

**Comment by jeffshee** [comment]
@shadyueh Hi, thanks for reporting. This should be solved together with #172.
