### ISSUE TITLE
Update Gnome runtime to version 46

### ISSUE THREAD

**Issue by CodeShakingSheep** [jeffshee/hidamari#172]
Hello,
First of all thank you for this wonderful app, I really enjoy it! On my system it's the last app that runs on Gnome 45 runtime. All other apps are already running on Gnome 46 or 47 runtime. So, I would like to get rid of Gnome 45 runtime (it takes ~1.1 GB on my system) and for that I kindly ask the Gnome runtime to be updated to version 46. When I check my installed flatpaks with `flatpak list --columns=runtime,name,ref` this is the output for Hidamari:

```
org.gnome.Platform/x86_64/45                                  Hidamari                                                      io.github.jeffshee.Hidamari/x86_64/stable
```

The Gnome runtime would need to be updated in this repository, see https://github.com/jeffshee/hidamari/blob/master/io.github.jeffshee.Hidamari.json#L4 as well as in the flathub repository, see https://github.com/flathub/io.github.jeffshee.Hidamari/blob/master/io.github.jeffshee.Hidamari.json#L4. Thank you.

**Comment by jeffshee** [comment]
@CodeShakingSheep Hi, thanks for the reminder, and I apologize for the delay.

I updated the runtime version to 47, and the changes have just been pushed to the Flathub.
https://github.com/flathub/io.github.jeffshee.Hidamari/pull/11
The update should be available on Flathub soon! 😉

**Comment by CodeShakingSheep** [comment]
Awesome, runtime has updated to 47 on my system. Thanks for the quick implementation @jeffshee! :rocket:

**Comment by CodeShakingSheep** [comment]
Hi @jeffshee ,
I'm having this issue again that Hidamari is one of the last apps on my system using Gnome runtime 47. I wanna get rid of Gnome Application Platform 47 which takes ~1GB. Can the runtime be updated to version 49 please? 🙏 

Edit: Gnome runtime 47 has officially been deprecated now, leading to 

<img width="563" height="85" alt="Image" src="https://github.com/user-attachments/assets/476c93f7-14c8-4fca-b01c-acfc89ad2e7f" />
