### ISSUE TITLE
VLC error message printed infinitely and crashed

### ISSUE THREAD

**Issue by jeffshee** [jeffshee/hidamari#19]
As titled, vlc might print these kind of error message infinitely and crashed the program eventually on some system.
```
[h264 @ 0x7f1068ccb180] get_buffer() failed
[h264 @ 0x7f1068ccb180] thread_get_buffer() failed
[h264 @ 0x7f1068ccb180] decode_slice_header error
[h264 @ 0x7f1068ccb180] no frame!
```

**Comment by jeffshee** [comment]
Original post #18

**Comment by jeffshee** [comment]
@rgomez96 Might need more infomation about the issue.
1. Is the issue only occur with multi-monitor setup but not with single-monitor setup?
2. What is the version of your vlc player? Mine is `3.0.11.1 Vetinari` by the way.

**Comment by rgomez96** [comment]
Apparently i'm using VLC 3.0.13-1. I think all versions after 3.0 are Vetinari but if not i don't really know how to confirm it. 

I've had this issue only while using multi-monitor so far. I've tested using both as single monitor for some hours and i don't get any crashes, even if I only use the 1280 x 1024 one. When i use multi-monitor both wallpapers are displayed correctly until it crashes.

Usually it takes less than 30 minutes to crash, i will continue to test single monitor and will update this post if i get a crash.

**Comment by jeffshee** [comment]
I see. I will try with multi monitor setup then, and see if I can get some error :+1:

**Comment by jeffshee** [comment]
Closed as the new release is out. Feel free to reopen if the issue still remains.
