### ISSUE TITLE
[Feature Request] Multi-monitor support

### ISSUE THREAD

**Issue by bachmannn** [jeffshee/hidamari#2]
**Bug**
* Video is only shown on ``display0`` when I have two monitors connected

**Fix**
Add support to replicate video on multiple monitors `display0, 1, 2, 3 etc`

Love it and want to say thanks also!

**Comment by jeffshee** [comment]
Hi, thanks for the report. 
I do want to provide support for multiple monitors, however, I couldn't test my code as I only have 1 monitor.
I will think a way to achieve it.
Thanks!

**Comment by E-Bachman** [comment]
> I will think a way to achieve it.

I found a way to run it on two displays by creating a new virtual screen with `xrandr` setting it as default in `xorg.conf`. It's a trick but I think since it solves #2 and #3, you can close the issue.

**Comment by jeffshee** [comment]
Support added in #13
