### ISSUE TITLE
The wallpaper starts playing again when I put a video to play in full screen.

### ISSUE THREAD

**Issue by rounnus** [jeffshee/hidamari#21]
I noticed that the wallpaper starts again when the program has realized that I have a maximized window and I go to see a video from any source in full screen. I noticed this while looking at my second screen.

**Comment by jeffshee** [comment]
@rounnus Hi, it seems that you have a dual monitor setup. What's your OS, desktop environment and is your session in X11 or Wayland?

**Comment by rounnus** [comment]
Hello, the operating system I have installed is **Debian**, the environment is **xfce** and the session is **x11**.

**Comment by rounnus** [comment]
Also, I do not know if it helps but I noticed that if I press the pause button and then open a window to maximize, it behaves in the same way (it starts again). Is it an issue with **xfce**?

**Comment by jeffshee** [comment]
@rounnus Hi, I can confirm the issue. Here is how I reproduce the issue:
1. Launch Hidamari
2. Right-click > Pause playback. Now the playback should be paused.
3. Maximize any window, the playback started, which it shouldn't.

Am I describing the same issue that you are trying to report here?

**Comment by rounnus** [comment]
Hi, yes this is exactly the issue.

**Comment by jeffshee** [comment]
@rounnus Hi, thanks for reporting. Should be fixed now. Please try the master branch at the moment (manual installation).
