### ISSUE TITLE
Love the simplicity of your program. However.

### ISSUE THREAD

**Issue by TheHatBoxGhost** [jeffshee/hidamari#23]
Is it possible to not have the popup on launch the says to use the right button click on the desktop.
AND
is it possible for it to remember the last wall paper at boot so I don't have to set it each time?

**Comment by TheHatBoxGhost** [comment]
I removed the popup on start, just need some advice how to auto use the last video background I applied. It's like every time the app starts its the first time.

**Comment by jeffshee** [comment]
@TheHatBoxGhost Sorry for the late reply. I think it is a bug for the program not saving the last video wallpaper it used. Try manually quit the program at once after setting the video wallpaper, that will trigger the autosave function. I will see if I have time to do a bug fix soon.

**Comment by TheHatBoxGhost** [comment]
I think what you said worked. I have noticed though when i shut down the
system gives a warning that vlc still running. Not a biggy, just thought id
mention it

**Comment by jeffshee** [comment]
Closed as the new release is out. Feel free to reopen if the issue still remains.
