### ISSUE TITLE
Support for Mouse Tracking

### ISSUE THREAD

**Issue by Justsnoopy30** [jeffshee/hidamari#26]
Could you add support for mouse pointer tracking when embedding websites so that they can be more interactive?

**Comment by jeffshee** [comment]
@Justsnoopy30 
Mouse pointer tracking should be working just fine. Can you provide me the website for me to test?

**Comment by Justsnoopy30** [comment]
https://mgz.me should work to show
Notice if you move the mouse around on the desktop, the scenes don't recognize it and don't move with your mouse movements.

**Comment by Justsnoopy30** [comment]
Any update on this?

**Comment by jeffshee** [comment]
Hi @Justsnoopy30 
Not yet but I had figured out that WebKitGTK was the cause of this issue and #36.
Some webpage has issues with WebKitGTK but works fine with modern browsers like Firefox, chrome, etc.
This could be resolved if we switch the chromium-based backend.

**Comment by jeffshee** [comment]
Still waiting for `cefpython` to add python 3.8++ support for Linux, so no ETA when will this be implemented, unfortunately....
https://github.com/cztomczak/cefpython/issues/546

**Comment by jeffshee** [comment]
Closed as won't fix. WebKitGTK really needs to catch up with the modern browsers and there's not much I can do.
