### ISSUE TITLE
Gnome Top Panel Disappears When Only Viewing Desktop

### ISSUE THREAD

**Issue by tokanada** [jeffshee/hidamari#30]
Hi, I'm not sure if this is an intended feature or an unavoidable consequence, but it appears that the video frame overlaps what would be Gnome's top panel. Is there any way to either resize the view so that the panel can still show, or better yet, force the panel to be on top?

I am currently using a local video with both static image and detect maximized window enabled.

**Comment by jeffshee** [comment]
Closed as the new release is out. Feel free to reopen if the issue still remains.

**Comment by chenxiex** [comment]
I still have this problem on my ubuntu 22.04.1LTS with gnome42.5 on wayland. I use the flatpak package. With DING enabled, the top panel works well; but when DING is disabled and hidamari is enabled, the top panel disappears.

**Comment by noahdigesu** [comment]
Same here :/

**Comment by sammypanda** [comment]
i'm experiencing this issue too Gnome 44.2 on Wayland
