### ISSUE TITLE
OpenGL 3.0 ES doesn't work on embedded sites

### ISSUE THREAD

**Issue by Justsnoopy30** [jeffshee/hidamari#36]
Seems whatever backend you use to show the websites doesn't recognize WebGL with opengl 3.0 ES in shader programs
Example: https://thecodetherapy.com/view/616408587cddb40026557af9
Scene doesn't render you'll see an error with `ERROR line:unsupported shader version` if you open the shader editor with the pencil icon at the top

**Comment by jeffshee** [comment]
Closed as won't fix. WebKitGTK really needs to catch up with the modern browsers and there's not much I can do.
