### ISSUE TITLE
Got problem installing this 

### ISSUE THREAD

**Issue by HUST-wjc** [jeffshee/hidamari#39]
Hi,I tried to use apt or dpkg to install hidamari, but it said "depency python3-pydubus can't be installed", same as python3-vlc.
I am using ubuntu 16.04 right now.
Do you know what may be the cause of this?
Also, when I try to use unsuccessful installed hidamri, terminal shows that 
"File "/usr/bin/hidamari", line 2, in <module>
    import server
  File "/usr/share/hidamari/server.py", line 4, in <module>
    from gi.repository import GLib
ModuleNotFoundError: No module named 'gi'
"
could be a dumb question, but I really don't know how to fix it

**Comment by jeffshee** [comment]
Hi,
If the deb package isn't working well, you might want to try the
installation script. Plus, the installation script installs from the latest
master branch so it could be even better than the package version.
Also, IIRC Ubuntu 16.04 is still using the Unity desktop environment by
default. As this software gears toward GNOME users, your mileage might be
different. I don't even think it will work, especially on the DE that's so
much different from the supported one.

PS: Ubuntu 16.04 is too old and had already EOL, maybe you should consider
upgrading it. ;)

**Comment by HUST-wjc** [comment]
Tried installation script on my Ubuntu, still not work. :(
Thanks for your advise, guess I have to upgrade my OS first.
