### ISSUE TITLE
RuntimeError: Cannot communicate with Gnome Shell!

### ISSUE THREAD

**Issue by lomirus** [jeffshee/hidamari#40]
Output:
```console
$ hidamari
Config JSON:
{'audio_volume': 50,
 'data_source': None,
 'is_detect_maximized': True,
 'is_mute': False,
 'is_static_wallpaper': True,
 'mode': None,
 'static_wallpaper_blur_radius': 5,
 'version': 2}
Mode: Null
Monitor: width 1920 height 1920
Traceback (most recent call last):
  File "/home/lomirus/.hidamari/utils.py", line 198, in eval
    raise RuntimeError("Cannot communicate with Gnome Shell!")
RuntimeError: Cannot communicate with Gnome Shell!
```

System Info:
```
OS: Manjaro Linux x86_64 
Host: 82B6 Lenovo Legion R7000 2020 
Kernel: 5.15.12-1-MANJARO 
Resolution: 1920x1080 
DE: GNOME 41.2 
WM: Mutter 
CPU: AMD Ryzen 5 4600H with Radeon Graphics (12) @ 3.000 
GPU: NVIDIA 01:00.0 NVIDIA Corporation TU117M 
GPU: AMD ATI 06:00.0 Renoir
Memory: 3451MiB / 15424MiB
```

Other Info:
```console
$ python --version
Python 3.10.1
```

**Comment by jeffshee** [comment]
Hi @lomirus 
Thanks for reporting. I can confirm the issue. It looks like the Dbus API of Gnome Shell broke due to the update. (It worked fine so far.) This probably will affect the maximized window detection.

(Sadly I'm busy at the moment, the fix might be late.)

**Comment by jeffshee** [comment]
Apparently, GNOME shell restricted the Dbus API call...
https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/a628bbc4
https://github.com/pop-os/cosmic/issues/275

Workaround might be needed. Close for now because nothing I can do to fix it atm.

**Comment by jeffshee** [comment]
For Gnome Wayland, you can try the below command in looking glass (Alt+F2, input `lg`):
```
global.context.unsafe_mode = true
```
It allows external programs to access the gnome DBus API (previous behavior)

**Comment by cata-lystic** [comment]
> For Gnome Wayland, you can try the below command in looking glass (Alt+F2, input `lg`):
> 
> ```
> global.context.unsafe_mode = true
> ```
> 
> It allows external programs to access the gnome DBus API (previous behavior)

This does work if you do it and then open Hidamari. Is there a way to make this command permanent so it doesn't have to be done on each reboot?
