### ISSUE TITLE
Possibility to choose another directory for videos

### ISSUE THREAD

**Issue by guibperes** [jeffshee/hidamari#42]
It's a good ideia to make possible to change the videos directory, i had an issue with the default videos directory, i use my OS in portuguese language and that changes the default directory name to Vídeos (with an accent), so i had to create another directory without the accent to resolve this.

**Comment by jeffshee** [comment]
@guibperes Thanks.
I think this is easy to fix. Could you provide me with the output of `xdg-user-dir VIDEOS` ? Is the output of the command point to your video directory in the Portuguese locale? If so then we might be able to utilize this.

**Comment by guibperes** [comment]
$ xdg-user-dir VIDEOS
/home/guilherme/Vídeos

Yes, points to videos directory in the Portuguese locale.

**Comment by jeffshee** [comment]
@guibperes 
Thanks. I had pushed a quick fix to the `master` branch.
Please reinstall the program by using the method described here (.deb and .rpm packages will not be updated at any time soon):
https://github.com/jeffshee/hidamari#installation-other-linux-
