### ISSUE TITLE
Gnome become no response when right clicking the desktop

### ISSUE THREAD

**Issue by lomirus** [jeffshee/hidamari#45]
When I installed hidamari the first time, and applied the video wallpaper, it worked fine. If then I quit hidamari without saving the config (like by rebooting), the hidamari can still start up as well. But after I saving the config file:
```diff
-    "mode": null,
-    "data_source": null,
+    "mode": "MODE_VIDEO",
+    "data_source": "/home/lomirus/Videos/Hidamari/video.mp4",
```
And then launch the hidamari, though it can just start up, and play the animation and you can even interact with the windows, after you right clicking the desktop, all windows become no response but the wallpaper still keeps playing. You can still move the cursor, and the gnome panel and dash dock still have the hover animation. But if try to click it, it won't launch any programs.

More info:
```
OS: Manjaro Linux x86_64 
Host: 82B6 Lenovo Legion R7000 2020 
Kernel: 5.15.21-1-MANJARO 
Resolution: 1920x1080 
DE: GNOME 41.3 
WM: Mutter 
CPU: AMD Ryzen 5 4600H with Radeon Graphics (12) @ 3.000GHz 
GPU: NVIDIA 01:00.0 NVIDIA Corporation TU117M
```

**Comment by pikojek** [comment]
I really love this app, i have both NVIDIA and AMD, when using AMD its working perfectly.
But when i change to NVIDIA it freeze after opening context menu on the desktop.
```
DE: GNOME 41.5 
WM: Mutter 
CPU: Intel i9-9900KF (16) @ 5.000GHz 
GPU: NVIDIA GeForce RTX 3060 Lite Hash Rate 
```
maybe this issue is related? https://github.com/jeffshee/hidamari/issues/11

**Comment by jeffshee** [comment]
Closed as the new release is out. Feel free to reopen if the issue still remains.
