### ISSUE TITLE
Missing dependency being listed (libwnck3)

### ISSUE THREAD

**Issue by DannyXjsu** [jeffshee/hidamari#49]
I followed the installation guide and installed all listed dependencies, but I assume the python package from Arch Linux doesn't install libwnck3. When running hidamari I was getting `ValueError: Namespace Wnck not available` so I searched and found out I needed to install libwnck3.
Be sure to mention this dependency to help other Arch users.

**Comment by jeffshee** [comment]
Hi @DannyXjsu, thanks for reporting.
Added dependency checking to the installation script.
