### ISSUE TITLE
Suggestion: Use OpenCL for video acceleration on GPU

### ISSUE THREAD

**Issue by bachmannn** [jeffshee/hidamari#5]
**Suggestion:** Use `opencl` for rendering the video on GPU. Some older CPU dont have proper decoders and so it takes up 70%+ usage. 

**Benefits:**
* Longer battery life
* Reduce CPU from 60-70% usage to 2-3%

Komorebi also uses CPU and that is one of the biggest faults, maybe Hidamari can overcome this challenge? Thanks!

**Comment by jeffshee** [comment]
Hmm...
Current implementation depends heavily on `ClutterGst` as the backend, and I'm not sure how to do this.

Some references:
https://discourse.gnome.org/t/best-way-to-render-video-with-gtk3-and-wayland/1077
https://stackoverflow.com/questions/63129603/making-gstreamer-video-audio-in-python-smooth-and-loop

**Comment by jeffshee** [comment]
Fix by #6 , please try the master branch! <3
