### ISSUE TITLE
Arch Linux

### ISSUE THREAD

**Issue by FelipeFMA** [jeffshee/hidamari#51]
It would be much better if you guys put hidamari in the AUR

**Comment by jeffshee** [comment]
Hi @FelipeFMA, thanks for the suggestion.

That would be better but since I'm not daily driving Arch Linux-based OS it will be hard for me to maintain the package.
Or ideally Flatpak! Package maintainer welcome =)

**Comment by ashroyxi** [comment]
i'd prefer compiling from src more than installing from flatpak.

**Comment by jeffshee** [comment]
You are welcome to package it to AUR. If you want to try, please refer to my comment here:
https://github.com/jeffshee/hidamari/issues/62#issuecomment-1236564443

**Comment by jeffshee** [comment]
Feel free to continue the discussion at https://github.com/jeffshee/hidamari/issues/62
