### ISSUE TITLE
Hidamari not working in Gnome Wayland

### ISSUE THREAD

**Issue by alexanderstueben** [jeffshee/hidamari#52]
Hello,
I wanted to give Hidamari a try because in the feature list is Wayland Support but i cant start it on Ubuntu 22.04 because of libwnck not working on Wayland.

On start i get this error message:

`Config JSON:
{'audio_volume': 50,
 'data_source': None,
 'is_detect_maximized': True,
 'is_mute': False,
 'is_static_wallpaper': True,
 'mode': None,
 'static_wallpaper_blur_radius': 5,
 'version': 2}
Mode: Null
Monitor: width 1920 height 1920
Monitor: width 1920 height 1920
Monitor: width 1920 height 1920

(hidamari:9862): Wnck-WARNING **: 09:04:00.909: libwnck is designed to work in X11 only, no valid display found
Traceback (most recent call last):
  File "/usr/bin/hidamari", line 3, in <module>
    server.run()
  File "/usr/share/hidamari/server.py", line 170, in run
    hidamari.dbus_published_callback()
  File "/usr/share/hidamari/server.py", line 48, in null
    self.player = NullPlayer(self.config)
  File "/usr/share/hidamari/null_player.py", line 12, in __init__
    super().__init__(config)
  File "/usr/share/hidamari/base_player.py", line 35, in __init__
    self.window_handler = WindowHandler(self._on_window_state_changed)
  File "/usr/share/hidamari/utils.py", line 104, in __init__
    self.screen.force_update()
AttributeError: 'NoneType' object has no attribute 'force_update'
`
If you know want I am doing wrong please help me out,
thank you :)

**Comment by jeffshee** [comment]
Hi @alexanderstueben, it seems the program couldn't detect that you are using Wayland. 
Could you please provide me the output of `echo $XDG_SESSION_TYPE`? Also, are you using GNOME?

**Comment by manthanf1** [comment]
Hi @jeffshee 

Not OP, but I have the same error output. 
`echo $XDG_SESSION_TYPE` returns `wayland`
I'm on Gnome 42.2.

Hope that helps!

**Comment by alexanderstueben** [comment]
Sorry for the late response, the command returns "wayland" for me and I'm using Gnome 42.1

**Comment by jeffshee** [comment]
Hi @manthanf1, @alexanderstueben 

Thanks!
The output seems right; unfortunately, I don't know what is going wrong. Sorry, but Wayland support tends to break here and there =(

**Comment by OneSons** [comment]
FWIW it seems to be working fine now. I'm using Wayland on Manjaro Gnome.

**Comment by jeffshee** [comment]
Closed as the new release is out. Feel free to reopen if the issue still remains.
