### ISSUE TITLE
Weird behavior on Wayland on Fedora 36

### ISSUE THREAD

**Issue by Freeplayg** [jeffshee/hidamari#54]
There's another issue with a similar title, but I think this is behaving differently... 

https://user-images.githubusercontent.com/40742947/175125963-e8b90bba-4c34-4fe1-b047-291ef943e837.mp4

(In my last issue, I was on Xorg)

**Comment by jeffshee** [comment]
Probably Wayland + Nvidia issue? Please try the recent master to see if the issue is fixed or not.

**Comment by Freeplayg** [comment]
It seems to be working now, thank you!
