### ISSUE TITLE
application not showing icons on pop os

### ISSUE THREAD

**Issue by Teru-dot-png** [jeffshee/hidamari#57]
i had a brief moment where i could see my icons i dont see any settings i could touch to fix it is this a glitch or it dossent have support to have icons at the same time?

**Comment by jeffshee** [comment]
Thanks for reporting. If you mean the desktop icons, try disable and enable
the gnome extension that provide the desktop icons on Pop OS (I believe it
use something similar to DING extension).

**Comment by JosephTheTank13** [comment]
I have this issue also.
