### ISSUE TITLE
install.sh does not properly work on 22.04

### ISSUE THREAD

**Issue by TS440S** [jeffshee/hidamari#58]
I used the supplied command from the github page, and it failed to install. Here is the log:

bash <(wget -qO- https://raw.githubusercontent.com/jeffshee/hidamari/master/install.sh)
=== Hidamari (Un)Installer Script ===
0 for uninstall
1 for install
Choose [0/1]?1
This will install Hidamari to /home/joseph/.local/share/hidamari
Do you wish to proceed [y/N]?y
Dependencies check OK
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pycairo in /usr/lib/python3/dist-packages (1.20.1)
Collecting pycairo
  Downloading pycairo-1.21.0.tar.gz (340 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 340.7/340.7 KB 7.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: PyGObject in /usr/lib/python3/dist-packages (3.42.0)
Collecting PyGObject
  Downloading PyGObject-3.42.2.tar.gz (719 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 719.5/719.5 KB 12.3 MB/s eta 0:00:00
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [41 lines of output]
      Collecting setuptools
        Using cached setuptools-63.2.0-py3-none-any.whl (1.2 MB)
      Collecting wheel
        Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting pycairo
        Using cached pycairo-1.21.0.tar.gz (340 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Building wheels for collected packages: pycairo
        Building wheel for pycairo (pyproject.toml): started
        Building wheel for pycairo (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
      
        × Building wheel for pycairo (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [15 lines of output]
            running bdist_wheel
            running build
            running build_py
            creating build
            creating build/lib.linux-x86_64-3.10
            creating build/lib.linux-x86_64-3.10/cairo
            copying cairo/__init__.py -> build/lib.linux-x86_64-3.10/cairo
            copying cairo/__init__.pyi -> build/lib.linux-x86_64-3.10/cairo
            copying cairo/py.typed -> build/lib.linux-x86_64-3.10/cairo
            running build_ext
            Package cairo was not found in the pkg-config search path.
            Perhaps you should add the directory containing `cairo.pc'
            to the PKG_CONFIG_PATH environment variable
            No package 'cairo' found
            Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.15.10']' returned non-zero exit status 1.
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for pycairo
      Failed to build pycairo
      ERROR: Could not build wheels for pycairo, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
PATH check OK
Cloning into '/home/joseph/.local/share/hidamari'...
remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 28 (delta 2), reused 9 (delta 0), pack-reused 0
Receiving objects: 100% (28/28), 461.40 KiB | 4.66 MiB/s, done.
Resolving deltas: 100% (2/2), done.

It did create a program though, and when I execute it I get this:

hidamari
/home/joseph/.local/share/hidamari/src/utils.py:10: PyGIWarning: GdkPixbuf was imported without specifying a version first. Use gi.require_version('GdkPixbuf', '2.0') before import to ensure that the right version gets loaded.
  from gi.repository.GdkPixbuf import Pixbuf
Config JSON:
{'audio_volume': 50,
 'data_source': None,
 'is_detect_maximized': True,
 'is_mute': False,
 'is_static_wallpaper': True,
 'mode': None,
 'static_wallpaper_blur_radius': 5,
 'version': 2}
Mode: Null
Traceback (most recent call last):
  File "/home/joseph/.local/bin/hidamari", line 33, in <module>
    server.run()
  File "/home/joseph/.local/share/hidamari/src/server.py", line 172, in run
    hidamari.dbus_published_callback()
  File "/home/joseph/.local/share/hidamari/src/server.py", line 49, in null
    from null_player import NullPlayer
  File "/home/joseph/.local/share/hidamari/src/null_player.py", line 6, in <module>
    from base_player import BasePlayer
  File "/home/joseph/.local/share/hidamari/src/base_player.py", line 22, in <module>
    from monitor import Monitor
  File "/home/joseph/.local/share/hidamari/src/monitor.py", line 2, in <module>
    import vlc
ModuleNotFoundError: No module named 'vlc'

After installing the VLC module, the program works but covers up the desktop icons until I quit the program.

**Comment by alexanderstueben** [comment]
I solved this problem by installing the package "python3-cairo-dev"
https://github.com/taylordotfish/harmony/issues/10

**Comment by shadyueh** [comment]
I followed your suggestion @alexanderstueben , then i got another similar error:

```
      copying gi/overrides/GLib.py -> build/lib.linux-x86_64-3.10/gi/overrides
      copying gi/overrides/keysyms.py -> build/lib.linux-x86_64-3.10/gi/overrides
      copying gi/overrides/GIMarshallingTests.py -> build/lib.linux-x86_64-3.10/gi/overrides
      copying gi/overrides/GObject.py -> build/lib.linux-x86_64-3.10/gi/overrides
      copying gi/overrides/Gdk.py -> build/lib.linux-x86_64-3.10/gi/overrides
      running build_ext
      Package glib-2.0 was not found in the pkg-config search path.
      Perhaps you should add the directory containing `glib-2.0.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'glib-2.0' found
      Command '('pkg-config', '--print-errors', '--exists', 'glib-2.0 >= 2.56.0')' returned non-zero exit status 1.
      
      Try installing it with: 'sudo apt install libglib2.0-dev'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for PyGObject
Failed to build PyGObject
ERROR: Could not build wheels for PyGObject, which is required to install pyproject.toml-based projects

```
So I'm atm trying install everything it is asking to see if the installation runs without errors.

**Comment by GUSTAVPEREIRA** [comment]
I just installed this lib sudo apt install libgirepository1.0-dev thats works for me.

**Comment by jeffshee** [comment]
Closed as the new release is out. Now you can use Flatpak~
