### ISSUE TITLE
Build for AUR

### ISSUE THREAD

**Issue by Shaurya-Kalia** [jeffshee/hidamari#62]
Sorry for posting as issue, but I could not find exact answer in the documentation, and the code seems to indicate that gnome is required, though it isn't mentioned explicitly

**Comment by jeffshee** [comment]
Hi @Shaurya-Kalia,
it should work with other DE as well, but not been tested. GNOME is the main target because that's what I'm using. You do not need GNOME to use Hidamari actually.

You also do not need to compile yourself. You just need to go to the release section, download the Flatpak and install it (for now). I'm currently waiting for Flathub's approval so maybe next time you can find Hidamari in your software center as well! =) 

I hope this answers your question.

**Comment by Shaurya-Kalia** [comment]
If possible, i would prefer to compile it. Maybe upload to AUR if I can

**Comment by jeffshee** [comment]
Hi @Shaurya-Kalia, it’s good to know that you have the intention to package Hidamari to your distro. It’s technically possible to do so.

Hidamari is written in Python, it is an interpreted language so you don’t compile. Just make a package to install the dependencies, and copy the scripts to the right places, then you are good to go.

If you need a reference, check [this](https://github.com/jeffshee/hidamari/blob/7d43950c250f978840407df13b37edeb4f6b9279/hidamari.spec). This is the SPEC file that I used to package for Fedora. (This is for v2, **so it’s outdated**!) Note that I don’t package for distro anymore, since almost every distro support Flatpak nowadays.

Bear in mind that, I only provide support for Flatpak installation in the future.

**Comment by laymoth** [comment]
Hi @Shaurya-Kalia, I just made the PKGBUILD, do you want to test it?

https://github.com/laymoth/hidamari-git

![Screenshot from 2022-09-09 08-27-25](https://user-images.githubusercontent.com/22806461/189254260-62dca7d3-221c-4062-9a66-c8fb2c6b98d4.png)

**Comment by laymoth** [comment]
I just made the PKGBUILD, anyone want to test it?

https://github.com/laymoth/hidamari-git

![Screenshot from 2022-09-09 08-27-25](https://user-images.githubusercontent.com/22806461/189254260-62dca7d3-221c-4062-9a66-c8fb2c6b98d4.png)

**Comment by Shaurya-Kalia** [comment]
> I just made the PKGBUILD, anyone want to test it?
> 
> https://github.com/laymoth/hidamari-git

Thanks for creating pkgbuild. I have been out for a while but will test and report as soon as I am back on my PC

**Comment by jeffshee** [comment]
@laymoth Thanks for contribution! 
Do you plan to maintain the package in the future?
Feel free to tell me if you want to be mentioned in the project’s README. (Probably in “Unofficial package” section)

**Comment by Shaurya-Kalia** [comment]
Well, I tried installing from the PKGBUILD and it does install correctly. However, trying to run it gives the error:
```
Traceback (most recent call last):
  File "/usr/share/hidamari/hidamari/__main__.py", line 6, in <module>
    from commons import *
ModuleNotFoundError: No module named 'commons'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/hidamari/hidamari/server.py", line 12, in <module>
    from commons import *
ModuleNotFoundError: No module named 'commons'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/hidamari/hidamari/gui/control.py", line 17, in <module>
    from commons import *
ModuleNotFoundError: No module named 'commons'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/hidamari", line 43, in <module>
    from hidamari import __main__ as main
  File "/usr/share/hidamari/hidamari/__main__.py", line 12, in <module>
    from hidamari import server
  File "/usr/share/hidamari/hidamari/server.py", line 22, in <module>
    from hidamari.gui.control import main as gui_main
  File "/usr/share/hidamari/hidamari/gui/control.py", line 22, in <module>
    from hidamari.gui.gui_utils import get_thumbnail, debounce
  File "/usr/share/hidamari/hidamari/gui/gui_utils.py", line 7, in <module>
    gi.require_version("GnomeDesktop", "4.0")
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GnomeDesktop not available
```
I think my initial suspicion was correct. It does require gnome (I am on kde). If the @jeffshee advises something else, I will try that too, as he claimed it would work in other DEs. Until then, it would be better to add `gnome-desktop` and `libwnck3` as dependencies in PKGBUILD

**Comment by Shaurya-Kalia** [comment]
> Thanks for contribution! Do you plan to maintain the package in the future? Feel free to tell me if you want to be mentioned in the project’s README. (Probably in “Unofficial package” section)

As far as the AUR pkgbuild is concerned, I don't think @laymoth will need to update it again as it simply downloads the latest code from hidamari repo. So unless a major change is made to structure of the file hierarchy or names, this pkgbuild will continue to work. One disadvantage of this approach though is that a user will have to initiate an update manually. If however @laymoth modifies the script to pick the code from Releases (`https://github.com/jeffshee/hidamari/archive/refs/tags/v3.0-beta3.tar.gz`for the latest for eg), they will have to update PKGBUILD each time a new release is pushed, but the user will get prompt for update

**Comment by laymoth** [comment]
> @laymoth Thanks for contribution! Do you plan to maintain the package in the future? Feel free to tell me if you want to be mentioned in the project’s README. (Probably in “Unofficial package” section)

Maybe I will maintain the package. But if anyone wants to maintain this package, I have no problem.

**Comment by jeffshee** [comment]
>I think my initial suspicion was correct. It does require gnome (I am on kde). 

Yep, you require `gnome-desktop` package. Don't worry, it's not the GNOME DE actually. That is just a little library with horrible naming. For dependencies, it might help to check the Flatpak manifest as well.

>If however @laymoth modifies the script to pick the code from Releases (https://github.com/jeffshee/hidamari/archive/refs/tags/v3.0-beta3.tar.gzfor the latest for eg), they will have to update PKGBUILD each time a new release is pushed, but the user will get prompt for update

Yep, that's a good idea to maintain the package. As a part of the workflow, I will tag a GitHub release each time I release an update on Flathub.

**Comment by jeffshee** [comment]
@laymoth `youtube-dl` is not longer used. You need `yt-dlp` instead.

**Comment by laymoth** [comment]
> > Thanks for contribution! Do you plan to maintain the package in the future? Feel free to tell me if you want to be mentioned in the project’s README. (Probably in “Unofficial package” section)
> 
> As far as the AUR pkgbuild is concerned, I don't think @laymoth will need to update it again as it simply downloads the latest code from hidamari repo. So unless a major change is made to structure of the file hierarchy or names, this pkgbuild will continue to work. One disadvantage of this approach though is that a user will have to initiate an update manually. If however @laymoth modifies the script to pick the code from Releases (`https://github.com/jeffshee/hidamari/archive/refs/tags/v3.0-beta3.tar.gz`for the latest for eg), they will have to update PKGBUILD each time a new release is pushed, but the user will get prompt for update

I've tried it, but got an error
```
+ exec meson setup --prefix /usr --libexecdir lib --sbindir bin --buildtype plain --auto-features enabled --wrap-mode nodownload -D b_lto=true -D b_pie=true hidamari build

ERROR: Neither directory contains a build file meson.build.
```

So I tried to add a tag to source
```
_pkgver=3.0-beta3
source=("git+https://github.com/jeffshee/hidamari.git#tag=v${_pkgver}")
```
And I think, it works

Beta2:

![Screenshot from 2022-09-09 21-19-07](https://user-images.githubusercontent.com/22806461/189372250-cdfa3c0a-a38e-4b57-9bb1-56ba9d819f8d.png)

Beta3:

![Screenshot from 2022-09-09 21-19-57](https://user-images.githubusercontent.com/22806461/189372552-c1fd02aa-3d59-4162-8269-f23269179484.png)

**Comment by laymoth** [comment]
> @laymoth `youtube-dl` is not longer used. You need `yt-dlp` instead.

Done!

**Comment by jeffshee** [comment]
@laymoth 
You should add these as dependencies too, `python-requests`, `libwnck3`
And also these as weak dependencies, `libappindicator-gtk3`, `mesa-utils`, `vdpauinfo`

**Comment by jeffshee** [comment]
@laymoth 
Also, I think it's not necessary to do `pip install -r requirements.txt` since you are already installing those Python dependencies through system packages.

**Comment by laymoth** [comment]
> @laymoth Anda harus menambahkan ini sebagai dependensi juga, `python-requests`, `libwnck3` Dan juga ini sebagai dependensi lemah, `libappindicator-gtk3`, `mesa-utils`,`vdpauinfo`



> @laymoth Juga, saya pikir itu tidak perlu dilakukan `pip install -r requirements.txt`karena Anda sudah menginstal dependensi Python tersebut melalui paket sistem.

Done, works fine on my VM :)

![Screenshot from 2022-09-10 08-03-31](https://user-images.githubusercontent.com/22806461/189462718-77612b74-89f2-404f-b13e-99c8869c71fd.png)

**Comment by laymoth** [comment]
> @laymoth You should add these as dependencies too, `python-requests`, `libwnck3` And also these as weak dependencies, `libappindicator-gtk3`, `mesa-utils`, `vdpauinfo`



> @laymoth Also, I think it's not necessary to do `pip install -r requirements.txt` since you are already installing those Python dependencies through system packages.

Done, works fine on my VM :)

![Screenshot from 2022-09-10 08-03-31](https://user-images.githubusercontent.com/22806461/189462718-77612b74-89f2-404f-b13e-99c8869c71fd.png)

**Comment by jeffshee** [comment]
@laymoth Thanks for the efforts!
The AUR package is mentioned here: https://github.com/jeffshee/hidamari#unofficial-package
Closed as completed!

**Comment by jeffshee** [comment]
Hi, I should work with other DE as well, but not tested. GNOME is the main
target because that's what I'm using.

With that said, feel free to report if you have any issue using Hidamari
with your DE.
