### ISSUE TITLE
HW acceleration issue

### ISSUE THREAD

**Issue by jeffshee** [jeffshee/hidamari#65]
@jeffshee Currently it uses mpv right? I can't get the hw acceleration to work with Hidamari (installed from Flathub) + MPV :/
Any way to force the `--hwdec=auto-safe` params?
I found the same issue in Celluloid Flatpak but loading an mpv config file with `hwdec=auto-safe` solved that for me

_Originally posted by @VarLad in https://github.com/jeffshee/hidamari/issues/64#issuecomment-1239800346_

**Comment by jeffshee** [comment]
@VarLad Could you please provide a log so I can investigate?
To do so, just run the app with debug flag `flatpak run io.github.jeffshee.Hidamari -d` and paste the output here.
Thanks!

**Comment by VarLad** [comment]
Thanks for shifting the issue! 
Here's the logs
```
libva info: VA-API version 1.12.0
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva info: VA-API version 1.12.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/radeonsi_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/GL/lib/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_12
libva info: va_openDriver() returns 0.
Xlib:  extension "NV-GLX" missing on display ":99.0".
Xlib:  extension "NV-GLX" missing on display ":99.0".
Xlib:  extension "NV-GLX" missing on display ":99.0".
```

**Comment by jeffshee** [comment]
If I'm not mistaken, `va_openDriver() returns 0.` which means the function exited without error. So it seems the HW acceleration actually works properly...
However, the next line `Xlib:  extension "NV-GLX" missing on display ":99.0"` is sus to me. 🤔

I'm guessing here, are you using an Nvidia card with the Wayland session?

**Comment by jeffshee** [comment]
Even better if you could paste the system information here. It should be the first thing output in the log.
Here is my example:
```
❯ flatpak run io.github.jeffshee.Hidamari -d
INFO:Hidamari:Hidamari v3.0-beta3
--- System information ---
is_gnome = True
is_wayland = False
is_nvidia_proprietary = True
is_vdpau_ok = True
is_flatpak = True
--------------------------
```

**Comment by RushingAlien** [comment]
i see that log sees vdpau, does vaapi work however?

**Comment by RushingAlien** [comment]
```
libva info: VA-API version 1.12.0
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva info: VA-API version 1.12.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/radeonsi_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/GL/lib/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_12
libva info: va_openDriver() returns 0
Failed to open VDPAU backend libvdpau_nvidia.so: tidak dapat membuka berkas objek terbagi: Tidak ada berkas atau direktori seperti itu
Failed to open VDPAU backend libvdpau_nvidia.so: tidak dapat membuka berkas objek terbagi: Tidak ada berkas atau direktori seperti itu
```
logs

**Comment by jeffshee** [comment]
@RushingAlien Hi, thanks for reporting.

Are you using Nvidia card in Wayland session? That’s not going to work at the moment (there is some issue with vlc side I believe). 
Please consider providing a detailed log as well, if possible. Especially the system information as mentioned above: https://github.com/jeffshee/hidamari/issues/65#issuecomment-1240698885

**Comment by jeffshee** [comment]
@RushingAlien 

> vo=gpu is also an mpv config to enable gpu output

It doesn’t use MPV, so config for MPV is not going to work here. =)
It uses VLC actually.

**Comment by jdfinch** [comment]
Hardware acceleration not working for me (X11).

Looks like a different problem than above though.

```
(base) flatpak run io.github.jeffshee.Hidamari -d
Gtk-Message: 20:41:30.855: Failed to load module "xapp-gtk3-module"
Error: couldn't find RGB GLX visual or fbconfig
INFO:Hidamari:Hidamari v3.0-beta4
--- System information ---
is_gnome = True
is_wayland = False
is_nvidia_proprietary = False
is_vdpau_ok = False
is_flatpak = True
--------------------------
INFO:Hidamari:[Args] {'p': 0, 'background': False, 'debug': True, 'reset': False}
DEBUG:Hidamari:[Config] Loaded /home/jdfinch/.var/app/io.github.jeffshee.Hidamari/config/hidamari/config.json
--------- Config ---------
{  'audio_volume': 0,
   'data_source': '/home/jdfinch/Videos/Hidamari/liquid.webm',
   'fade_duration_sec': 1.5,
   'fade_interval': 0.1,
   'is_detect_maximized': True,
   'is_first_time': False,
   'is_mute': False,
   'is_show_systray': False,
   'is_static_wallpaper': True,
   'mode': 'MODE_VIDEO',
   'static_wallpaper_blur_radius': 5,
   'version': 3}
--------------------------
INFO:Hidamari:[Mode] MODE_VIDEO
INFO:Hidamari:[Server] Started
Gtk-Message: 20:41:31.062: Failed to load module "xapp-gtk3-module"
Gtk-Message: 20:41:31.103: Failed to load module "xapp-gtk3-module"
Gtk-Message: 20:41:31.212: Failed to load module "canberra-gtk-module"
Gtk-Message: 20:41:31.212: Failed to load module "pk-gtk-module"
Gtk-Message: 20:41:31.225: Failed to load module "canberra-gtk-module"
Gtk-Message: 20:41:31.225: Failed to load module "pk-gtk-module"
DEBUG:Hidamari:[Config] Loaded /home/jdfinch/.var/app/io.github.jeffshee.Hidamari/config/hidamari/config.json
--------- Config ---------
{  'audio_volume': 0,
   'data_source': '/home/jdfinch/Videos/Hidamari/liquid.webm',
   'fade_duration_sec': 1.5,
   'fade_interval': 0.1,
   'is_detect_maximized': True,
   'is_first_time': False,
   'is_mute': False,
   'is_show_systray': False,
   'is_static_wallpaper': True,
   'mode': 'MODE_VIDEO',
   'static_wallpaper_blur_radius': 5,
   'version': 3}
--------------------------
libEGL warning: DRI3: Screen seems not DRI3 capable
libEGL warning: DRI2: failed to authenticate
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
libEGL warning: DRI3: Screen seems not DRI3 capable
libEGL warning: DRI2: failed to authenticate

```

When I run VLC and play a video it does use hw acceleration.

**Comment by jeffshee** [comment]
Hi @jdfinch ,

>Error: couldn't find RGB GLX visual or fbconfig

Just a quick tip, if you have recently updated your graphic driver, do make sure that you have to update the Flatpak's one as well to match the driver's version. A reboot after the driver update helps as well sometimes.

In short, please try `flatpak update` and reboot first. Let me know if the issue still persists. 😃

**Comment by jdfinch** [comment]
@jeffshee 

> Just a quick tip, if you have recently updated your graphic driver, do make sure that you have to update the Flatpak's one as well to match the driver's version. A reboot after the driver update helps as well sometimes.

Thank you so much for this. I didn't realize flatpaks couldn't access my driver without installing the driver as a flatpak as well.

Everything works now as expected! :smile:

**Comment by vmath3us** [comment]
please, update intel-vaapi to 22.08, like vlc upstream.
