### ISSUE TITLE
V3 not working unlike V2 ¿? Failed to load module "xapp-gtk3-module"

### ISSUE THREAD

**Issue by ignaciomaybe** [jeffshee/hidamari#68]
Thanks for the work on the program, it's actually very cool, first time doing a issue (newbie dude) so if i need to provide more info please let me know.
The issue is that on the V2 everything worked fine on my system (Linux Mint 20.3 xfce4 version w\default Xfwm4 WM, and the requested libraries for Hidamari to run like python3-pip, pillow, etc ). Installed the OS on a new hard drive and now with the V3 being on Flathub doesn't seem to work (sudo updated and upgraded before running the install of course). Installed everything that flatpak showed for installing the software, doesn't seem to work on any of the 3 modes. It always shows the same error 'Gtk-Message: 21:34:15.442: Failed to load module "xapp-gtk3-module" '.  Tried to install libxapp-dev to see if it needed a specific library, xapps-common also didn't fix the issue. As it seem everytime i try to use any mode of Hidamari after the gtk error message shows first a problem with the line containing: ' _bootstrap self.run() '  first and then more conflicts with other lines. It also shows a weird ' No such key “picture-uri-dark” ' message after the attempt on video mode becasue of: ' gsettings get org.gnome.desktop.background picture-uri-dark'. 
Hope the question it's not something super stupid, adding some captures showing the Terminal when using Hidamari since maybe the explanation it's ultra abstract.
 
![Captura01](https://user-images.githubusercontent.com/85526569/191150349-c9a6762e-e5ae-4369-af56-15f398c7247e.png)
![Captura02](https://user-images.githubusercontent.com/85526569/191150353-807d1c93-0880-47e7-a0d5-d75ab35e41f3.png)
![Captura03](https://user-images.githubusercontent.com/85526569/191150356-0f7b2789-b13e-4f4a-9da2-6ae326394b26.png)

**Comment by jeffshee** [comment]
@ignaciomaybe Hi, thanks for reporting.

Fixing this issue now, should be done soon =)

**Comment by jeffshee** [comment]
Hi @ignaciomaybe , thanks for reporting!

The fix is in the latest build! An update should be available on Flathub a few hours later 😎

Closed as fixed. Feel free to reopen this issue if the update doesn't solve the problem =)
