### ISSUE TITLE
autostart after login not working on Pop!_OS 22.04 LTS

### ISSUE THREAD

**Issue by expl0r3rgu1** [jeffshee/hidamari#69]
When I launch the hidamari application the live wallpaper that I previously set returns, I went to check the autostart after login quick toggle status and it disabled itself with the reboot.

**Comment by jeffshee** [comment]
Hi @expl0r3rgu1, thanks for reporting!

The fix is in the latest build! An update should be available on Flathub a few hours later 😎

Closed as fixed. Feel free to reopen this issue if the update doesn't solve the problem =)
