### ISSUE TITLE
The desktop icons are disappearing when applying the video wallpaper on ZorinOS

### ISSUE THREAD

**Issue by d4f5409d** [jeffshee/hidamari#73]
I can't do anything on my desktop because of this.

OS: ZorinOS 16.1
X11

**Comment by jeffshee** [comment]
Hi @d4f5409d,

Thanks for report~
Desktop icons support on ZorinOS was added. Please wait for the next release (I'll do it in this weekend if possible)

**Comment by d4f5409d** [comment]
Thank you so much! 🤩

**Comment by jeffshee** [comment]
Closed as completed
