### ISSUE TITLE
Add "Desktop Settings" context menu

### ISSUE THREAD

**Issue by keteague** [jeffshee/hidamari#76]
"Desktop Settings" isn't available from the Hidamari context menu when I right-click on the desktop.  The only way to get to the Desktop Settings is to go through Settings.

**Comment by jeffshee** [comment]
Hi @keteague 

While it is possible to add an entry that launches the Desktop Settings to the Hidamari context menu, I decided not to add it.
1. Different distro/DE have different commands to launch the desktop setting, and I don't want to add too much GNOME-specific stuff here.
2. Launching the desktop setting from Hidamari requires breaking the Flatpak sandbox.
