### ISSUE TITLE
Playback stops when super key is pressed

### ISSUE THREAD

**Issue by keteague** [jeffshee/hidamari#77]
Video playback stops (and reverts back to showing the previously selected wallpaper) when the super key is pressed in Gnome to display the running applications.

**Comment by jeffshee** [comment]
Hi @keteague 

It's kind of hard to explain... Actually, the video playback doesn't stop. In fact, the wallpaper you see in activities view (that you see when you press the super key) is a static wallpaper. GNOME simply uses the static wallpaper when displaying the activities view. That's GNOME's behavior that Hidamari can't control. 

As a workaround, Hidamari provides a feature to automatically apply a frame of the video as the static wallpaper (and revert it to the original one when quit). The original wallpaper will be shown in the activities view if the "apply static wallpaper" is disabled.

P/s: If you want live wallpaper in the activities view as well, check the hanabi extension mentioned in README.
