### ISSUE TITLE
Video playback prevents timed screen lock

### ISSUE THREAD

**Issue by keteague** [jeffshee/hidamari#78]
In Gnome > Settings > Power > Power Savings Options:

- Screen Blank is ignored if Hidamari is running

**Comment by ajbucci** [comment]
It looks like this isn't fixed for me on hidamari v3.3 and vlc version 3.0.18. I'm wondering if something has changed in VLC since https://github.com/jeffshee/hidamari/commit/401c280d11848a2635a0ff7c070e7842dc9ae2ef? When I list my VLC media flags I do not see 'no-disable-screensaver'.
