### ISSUE TITLE
Gnome Top Panel and Dock Disappears When Only Viewing Desktop

### ISSUE THREAD

**Issue by claufedacosta** [jeffshee/hidamari#92]
It appears that the video frame overlaps what would be Gnome's top panel and the dock generated by the dash to dock gnome extension when there are no windows on the workspace/monitor.

This seem to be the same problem as: https://github.com/jeffshee/hidamari/issues/30

I have 2 monitors, with the multiple workspaces only available in the main monitor. When switching to the first workspace, and there is at least 1 window in the main monitor, there is no bug in the secondary monitor, but switching to any other workspace triggers again this problem to the second monitor

CPU: AMD Ryzen™ 5 3400G
GPU: AMD Radeon™ Vega 11 (integrated)
Kernel: 5.15.85-1-MANJARO
DE: Gnome 43.2 Wayland
Hidamari 3.2 installed from flatpak

The dock is configured with the smart hiding. When affected by this bug, and I move the mouse to make the dock appear, both the top panel and dock appear and disappears like blinking.
I tried to record this behavior, but in OBS pipewire monitor capture it appears all normal, as if there where no issue at all.

**Comment by claufedacosta** [comment]
Great job, BTW

**Comment by claufedacosta** [comment]
I was tinkering a bit and it seems that disabling "Gnome 4x UI Improvements" extension and rebooting solves the problem, it might just be a problem with that
Should have tried to disable al complements before opening this report

**Comment by chenxiex** [comment]
> I was tinkering a bit and it seems that disabling "Gnome 4x UI Improvements" extension and rebooting solves the problem, it might just be a problem with that Should have tried to disable al complements before opening this report

I have the same problem. But with all extensions disabled, the problem still existed. The only way to avoid this problem for me seems to be enabling the old version of DING extension.

**Comment by PastaLaPate** [comment]
Seems to reappear when using the super key. Also seems to only affect Wayland. Tested on Zorin Os 18.1 Wayland Kernel: 6.17.0
